# Generated by Django 3.2.5 on 2021-07-30 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0003_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amountbackers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='final_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='default title', max_length=50),
            preserve_default=False,
        ),
    ]
