# Generated by Django 3.2.5 on 2021-07-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0004_auto_20210730_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='goodcause',
        ),
        migrations.AddField(
            model_name='listing',
            name='project',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
