# Generated by Django 3.2.5 on 2021-07-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0005_auto_20210730_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='goodcause',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='project',
            field=models.BooleanField(default=0),
        ),
    ]
