# Generated by Django 3.2.5 on 2021-07-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0006_auto_20210730_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='final_date',
            field=models.DateField(),
        ),
    ]
