# Generated by Django 3.2.5 on 2021-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0007_alter_listing_final_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures'),
        ),
    ]
