# Generated by Django 3.2.5 on 2021-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0015_alter_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='donated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
