# Generated by Django 3.2.5 on 2021-08-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0017_auto_20210802_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(default='Description of User', max_length=256),
        ),
    ]
