# Generated by Django 3.2.5 on 2021-08-03 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0018_user_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='goal',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(10)]),
        ),
    ]
