# Generated by Django 3.2.5 on 2021-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0019_alter_listing_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
