# Generated by Django 3.2.5 on 2021-08-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0020_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cswebfunding.listing')),
            ],
        ),
    ]
