# Generated by Django 3.2.5 on 2021-08-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0021_custombadge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomBadge',
        ),
    ]
