# Generated by Django 3.2.5 on 2021-08-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cswebfunding', '0023_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='amountbackers',
        ),
    ]
